language: python
python:
  - "3.6"

install:
  - pip install pandas
  - pip install pyodbc
  - pip install mysql-connector
  - pip install numpy
  - pip install missingno
  - pip install matplotlib
  
script:
  - python testcleanup.py
  - python teststats.py
  - python testodbc.py
  - python testmysql.py